version: '1.0'
name: gin-blog-master
displayName: gin-blog-master
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-e8193c1f
    displayName: 编译打包
    strategy: naturally
    trigger: auto
    executor:
      - alexcld
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: https://hub.docker.com/
        username: alexcld
        password: ywz0207.
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: true
        notify:
          - certificate: 8b872d00-fe6b-013a-bc4b-4ed97ba66370
            events:
              - skip
              - cancel
              - fail
              - success
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
