version: '1.0'
name: gin-blog-master
displayName: gin-blog-master
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-e8193c1f
    displayName: 编译打包
    strategy: naturally
    trigger: auto
    executor:
      - alexcld
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.17'
        commands:
          - '# 默认使用goproxy.cn'
          - export GOPROXY=https://goproxy.cn
          - '# 输入你的构建命令'
          - go build .
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches:
          - /go/pkg/mod
        notify:
          - certificate: 8b872d00-fe6b-013a-bc4b-4ed97ba66370
            events:
              - skip
              - cancel
              - fail
              - success
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
